import {
  HomeImage1,
  HomeImage10,
  HomeImage11,
  HomeImage12,
  HomeImage2,
  HomeImage3,
  HomeImage4,
  HomeImage5,
  HomeImage6,
  HomeImage7,
  HomeImage8,
  HomeImage17,
  HomeImage19,
  HomeImage22,
  HomeImage25,
  HomeImage26,
  HomeImage27,
  HomeImage28,
} from "@/src/assets/homeImages";
import { IHeroData } from "./homeHeroCarousel.props";

export const heroData: IHeroData[] = [
  {
    id: 1,
    title: "Sargordan zamin",
    slug: "sargordan-zamin",
    category: "komedya",
    image: HomeImage1,
    description: "Sargordan zamin 2017",
  },
  {
    id: 2,
    title: "Riverdeyl",
    slug: "riverdeyl",
    category: "drama",
    image: HomeImage2,
    description: "Riverdeyl kino filmi 2017",
  },
  {
    id: 3,
    title: "Qora minora",
    slug: "qora-minora",
    category: "komedya",
    image: HomeImage3,
    description: "Qora minora kino filmi 2017",
  },
  {
    id: 4,
    title: "Chumoli odam",
    slug: "chumoli-odam",
    category: "komedya",
    image: HomeImage4,
    description: "Chumoli odam kino filmi 2017",
  },
  {
    id: 5,
    title: "65 million yil aval",
    slug: "65-million-yil-aval",
    category: "komedya",
    image: HomeImage5,
    description: "Riverdeyl kino filmi 2017",
  },
  {
    id: 6,
    title: "Vikinglar",
    slug: "vikinglar",
    category: "komedya",
    image: HomeImage6,
    description: "65 million yil aval kino filmi 2017",
  },
  {
    id: 7,
    title: "Vampirlar kundaligi",
    slug: "vampirlar-kundaligi",
    category: "komedya",
    image: HomeImage7,
    description: "Vampirlar kundaligi kino filmi 2017",
  },
  {
    id: 8,
    title: "Jodugar",
    slug: "jodugar",
    category: "komedya",
    image: HomeImage8,
    description: "Vampirlar kundaligi kino filmi 2017",
  },
  {
    id: 9,
    title: "Grim",
    slug: "grim",
    category: "komedya",
    image: HomeImage28,
    description: "Grim kino filmi 2017",
  },
  {
    id: 10,
    title: "Bo'rilar to'dasi",
    slug: "bo'rilar-to'dasi",
    category: "komedya",
    image: HomeImage27,
    description: "Bo'rilar to'dasi kino filmi 2017",
  },
  {
    id: 11,
    title: "Birinchhi jodugar",
    slug: "Birinchhi jodugar",
    category: "komedya",
    image: HomeImage26,
    description: "Birinchhi jodugar kino filmi 2017",
  },
  {
    id: 12,
    title: "Shazam 2",
    slug: "shazam-2",
    category: "fantastik",
    image: HomeImage25,
    description: "Shazam 2 kino filmi 2017",
  },
];
